---

- name: base install
  hosts: all
  become: true
  gather_facts: false
  tags:
  - never
  - install
  roles:
    - role: base/install

- name: update ssh authorized_keys
  hosts: all
  gather_facts: false
  roles:
    - role: base/authorized_keys
