---
- name: setting up videosources desktop/graphics
  hosts: videosources
  become: true
  serial: 1
  roles:
  - role: video-desktop
  tags:
  - never
  - install

- name: setting up jitsi-drones
  hosts: jitsi_drones
  become: true
  serial: 1
  roles:
  - role: install-remotestudio
  - role: video-jitsi-client

