---
- name: setting up videosources desktop/graphics
  hosts: videosources
  become: true
  serial: 1
  roles:
  - role: video/hdmi-desktop
  tags:
  - never
  - install

- name: setting up jitsi-drones
  hosts: jitsi_drones
  become: true
  serial: 1
  roles:
  - role: remotestudio/install
  - role: video/jitsi-client

- name: setting up pi_audio settings
  hosts: pi_audio
  become: true
  roles:
  - role: audio/pi-usb-audio
  tags:
  - never
  - install

- name: setting up mpd pausenmusik
  hosts: music
  become: true
  roles:
  - role: audio/mpd-music
  tags:
  - never
  - install

- name: setting up nginx rtmp servers
  hosts: rtmp
  become: true
  roles:
  - role: video/nginx-rtmp
  tags:
  - never
  - install
  - rtmp
  - stream

- name: setting up decklink video encoders
  hosts: decklink_encoders
  become: true
  roles:
  - role: video/decklink-encoder
  vars:
    decklink_encoder_device: "{{ decklink_device }}"
    decklink_encoder_format_code: "{{ decklink_format_code }}"
  tags:
  - never
  - install
  - decklink
  - stream

