---
- name: setting up videosources desktop/graphics
  hosts: videosources
  become: true
  serial: 1
  roles:
  - role: video-desktop
  tags:
  - never
  - install

- name: setting up jitsi-drones
  hosts: jitsi_drones
  become: true
  serial: 1
  roles:
  - role: install-remotestudio
  - role: video-jitsi-client

- name: setting up pi_audio settings
  hosts: pi_audio
  become: true
  roles:
  - role: pi-usb-audio
  tags:
  - never
  - install

- name: setting up mpd pausenmusik
  hosts: music
  become: true
  roles:
  - role: mpd-music
  tags:
  - never
  - install

