- hosts: jitsi_servers
  become: true
  roles:
     - base/systemli.letsencrypt
     - video/jitsi-server/systemli.jitsi_meet
  post_tasks:
  - name: UFW ports
    ufw:
      rule: allow
      port: '{{ item }}'
      proto: tcp
    with_items:
      - '80'
      - '443'
      - '4443'
  - name: UFW ports udp
    ufw:
      rule: allow
      port: '{{ item }}'
      proto: udp
    with_items:
      - '10000'
  - name: start nginx
    service:
      name: nginx
      state: started
