---
- name: ensure desktop user is present, set groups
  ansible.builtin.user:
    name: "{{ desktop_username }}"
    shell: /bin/bash
    groups: audio,video
    append: yes
    state: present

- name: Install desktop packages
  ansible.builtin.apt:
    state: present
    name: [ task-lxde-desktop, pulseaudio, pavucontrol, unclutter, chromium, chromium-driver, molly-guard, nextcloud-desktop ]

- name: enable lightdm autologon
  ansible.builtin.blockinfile:
    path: /etc/lightdm/lightdm.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: '#exit-on-failure=false'
    content: |
      autologin-user={{ desktop_username }}
      autologin-user-timeout=0
      exit-on-failure=false
  notify: restart display

# restart lightdm to init config structure
- meta: flush_handlers

- name: set up desktop
  include_tasks: desktop-setup.yml

- name: set up pulseaudio
  include_tasks: pulseaudio.yml

- name: set up vnc (set desktop_vnc_password to enable)
  include_tasks: vnc.yml
  when: (desktop_vnc_password is defined)
