# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.define "jitsiserver1"

  config.vm.provider 'virtualbox' do |vb|
    vb.linked_clone = true
  end

  # disable vbox addons update
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
    config.vbguest.no_install = false
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision "ansible" do |ansible|
    ansible.become = true
    ansible.playbook = "../base.yml"
    ansible.tags = "install"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.become = true
    ansible.playbook = "../jitsi.yml"
    ansible.groups = {
      "jitsi_servers" => ["jitsiserver1"]
    }
  end

end
