---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: bionic64-repo
    box: ubuntu/bionic64
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  become: True
