---
- name: ensure packages for docker-compose repo
  apt:
    state: present
    name: [ apt-transport-https, ca-certificates, curl, gnupg2, software-properties-common ]

- name: docker apt key
  apt_key:
    keyserver: keys.gnupg.net
    id: 8D81803C0EBFCD88
    state: present 

- name: docker repo
  apt_repository:
    repo: 'deb https://download.docker.com/linux/debian {{ ansible_lsb.codename|lower }} stable'
    state: present
    filename: 'docker'
    update_cache: yes

- name: Install docker-compose
  apt:
    name: [ docker-ce, docker-compose ]
    state: present

- name: docker-compose config directory
  file:
    path: "{{ docker_compose_project_dir }}"
    state: directory

- name: docker-compose service unit
  template:
    src: files/docker-compose-service-unit.j2
    dest: '/etc/systemd/system/docker-compose@.service'
