---
name: kubic
style: line
url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ 'x' if ansible_distribution == 'Ubuntu' else ''}}{{ ansible_distribution }}_{{ ansible_distribution_version }}/
suites: /
key_path: kubic.asc
packages:
  - fuse-overlayfs
  - podman
  - slirp4netns
