---
- name: Install python3 dependencies
  apt:
    state: present
    name: [ git, python3-dev, python3-venv, python3-setuptools, python3-virtualenv, virtualenv, python3-setuptools-git, python3-wheel ]

- name: install venv
  pip:
    requirements: "{{ remotestudio_rootdir }}/src/control/requirements.txt"
    virtualenv: "{{ c3lingo_workspace }}/venv"
    virtualenv_python: python3


- name: install gunicorn
  pip:
    name:
    - gunicorn
    - eventlet
    virtualenv: "{{ c3lingo_workspace }}/venv"
    virtualenv_python: python3

# setup
